<?php

namespace kisRegBundle\Repository;

/**
 * GrupaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GrupaRepository extends \Doctrine\ORM\EntityRepository
{
}
