<?php

namespace kisRegBundle\Repository;

/**
 * ZajeciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ZajeciaRepository extends \Doctrine\ORM\EntityRepository
{
}
